version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhonsound/espereanza-backend
    ports:
      - "5000:5000"
    environment:
      - DATA_BASE_HOST=db
      - DATA_BASE_PORT=5432
      - DATA_BASE_USERNAME=postgres
      - DATA_BASE_HOST_PASSWORD=CallahanPerro
      - DATA_BASE_NAME=postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CallahanPerro
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: