export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const MISSION_REPOSITORY = 'MISSION_REPOSITORY';
export const LEVEL_REPOSITORY = 'MISSION_REPOSITORY';
export const EXERCISES_REPOSITORY = 'MISSION_REPOSITORY';
