export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const EMPLOYEE_REPOSITORY = 'EMPLOYEE_REPOSITORY';
export const BLACK_LIST_REPOSITORY = 'BLACK_LIST_REPOSITORY';
export const CLIENT_REPOSITORY = 'CLIENT_REPOSITORY';
export const STAFF_CLIENT_REPOSITORY = 'STAFF_CLIENT_REPOSITORY';
